# see https://wiki.hypr.land/configuring/window-rules/ for more
# see https://wiki.hypr.land/configuring/workspace-rules/ for workspace rules

# example windowrules that are useful

windowrule {
    # ignore maximize requests from all apps. you'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # fix some dragging issues with xwayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
