#!/bin/bash

# Raw Colors
C_RESET="\e[0m"
C_RED="\e[31m"
C_GREEN="\e[32m"
C_YELLOW="\e[33m"
C_BLUE="\e[34m"
C_CYAN="\e[36m"

# Backgrounds
C_BG_WHITE_FG_BLACK="\e[1;47;30m"
C_BG_MAGENTA_FG_BLACK="\e[45;30m"

# Formatted Tags
TAG_SKIP="${C_BG_WHITE_FG_BLACK}[SKIP]${C_RESET}"
TAG_PACMAN="${C_YELLOW}[PACMAN]${C_RESET}"
TAG_AUR="${C_BLUE}[AUR]${C_RESET}"
TAG_BOOT="${C_GREEN}[BOOTLOADER]${C_RESET}"
TAG_PKG="${C_CYAN}[PACKAGE]${C_RESET}"
TAG_DISPLAY="${C_BG_MAGENTA_FG_BLACK}[DISPLAYMANAGER]${C_RESET}"
TAG_ERROR="${C_RED}[ERROR]${C_RESET}"
TAG_INFO="${C_GREEN}[INFO]${C_RESET}"
